# CPU-only native emission; every run gets a fresh, retained artifact directory.
if(NOT DEFINED TEST_EXECUTABLE OR NOT EXISTS "${TEST_EXECUTABLE}")
  message(FATAL_ERROR "TEST_EXECUTABLE must name the built native test target")
endif()
if(NOT DEFINED ARTIFACT_ROOT OR ARTIFACT_ROOT STREQUAL "")
  message(FATAL_ERROR "ARTIFACT_ROOT must name the build-local test-artifacts directory")
endif()
file(MAKE_DIRECTORY "${ARTIFACT_ROOT}")
string(TIMESTAMP run_stamp "%Y%m%dT%H%M%S" UTC)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_nonce)
set(output "${ARTIFACT_ROOT}/unnormalized-${run_stamp}-${run_nonce}")
if(EXISTS "${output}")
  message(FATAL_ERROR "Refuse reused normalization artifact path: ${output}")
endif()
execute_process(COMMAND "${TEST_EXECUTABLE}" --unnormalized-coordinate-prepare-only "${output}"
  RESULT_VARIABLE result TIMEOUT 120)
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "CPU normalization preparation failed: ${result}; artifacts retained at ${output}")
endif()
message(STATUS "CPU normalization artifacts retained at ${output}")
